/**
 * Ghost Player Seed Data — 150 authentic EQ2-style characters.
 * All start at level 1 and progress organically from the newbie zones.
 * Personalities shape combat style, world events, and economy participation.
 *
 * personality: one of 300 named personality labels from ghostPersonalities.ts
 *              (e.g. "the Berserker", "the Wanderer")
 * activeHoursStart / activeHoursEnd: UTC hours (0-23) defining the ghost's
 *   active window. Wrap-around is supported (end < start means overnight).
 *   Seeds without these fields default to always-active (0-23).
 */

// Re-export GhostPersonality from ghostPersonalities so importers of this module
// that previously imported GhostPersonality from here continue to work.
export type { GhostPersonality } from "./ghostPersonalities.js";

export interface GhostSeed {
  name: string;
  race: string;
  class: string;
  archetype: string;
  alignment: "Qeynos" | "Freeport" | "Neutral";
  /** One of 300 personality labels from ghostPersonalities.ts, e.g. "the Berserker" */
  personality: string;
  level: number;
  xp: number;
  gold: number;
  zone: string;
  killCount: number;
  deathCount: number;
  bossKills: number;
  totalGoldEarned: number;
  totalGoldSpent: number;
  stats: {
    strength: number; agility: number; stamina: number;
    intelligence: number; wisdom: number; charisma: number;
  };
  /** UTC hour when this ghost comes online (0-23). Default: 0 (always active). */
  activeHoursStart?: number;
  /** UTC hour when this ghost goes offline (0-23). Default: 23 (always active). */
  activeHoursEnd?: number;
}

export const GHOST_SEEDS: GhostSeed[] = [
  {
    name: "Tharindel",
    race: "High Elf", class: "Wizard", archetype: "Mage", alignment: "Qeynos",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 12, stamina: 14, intelligence: 52, wisdom: 38, charisma: 20 },
  },
  {
    name: "Morigath",
    race: "Dark Elf", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 45, agility: 22, stamina: 40, intelligence: 18, wisdom: 14, charisma: 10 },
  },
  {
    name: "Sylvarra",
    race: "Wood Elf", class: "Ranger", archetype: "Scout", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 48, stamina: 22, intelligence: 16, wisdom: 18, charisma: 14 },
  },
  {
    name: "Durgrak",
    race: "Ogre", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 60, agility: 14, stamina: 55, intelligence: 8, wisdom: 10, charisma: 6 },
  },
  {
    name: "Liria Sunwhisper",
    race: "Fae", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 30, stamina: 16, intelligence: 22, wisdom: 44, charisma: 28 },
  },
  {
    name: "Zhangar",
    race: "Sarnak", class: "Inquisitor", archetype: "Priest", alignment: "Freeport",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 22, agility: 18, stamina: 28, intelligence: 30, wisdom: 55, charisma: 20 },
  },
  {
    name: "Kelindra",
    race: "Kerra", class: "Swashbuckler", archetype: "Scout", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 24, agility: 50, stamina: 20, intelligence: 14, wisdom: 12, charisma: 22 },
  },
  {
    name: "Brunnhildr",
    race: "Barbarian", class: "Berserker", archetype: "Fighter", alignment: "Qeynos",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 55, agility: 20, stamina: 50, intelligence: 10, wisdom: 12, charisma: 14 },
  },
  {
    name: "Naxxaril",
    race: "Arasai", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 20, stamina: 14, intelligence: 52, wisdom: 20, charisma: 16 },
  },
  {
    name: "Tumblefoot",
    race: "Gnome", class: "Illusionist", archetype: "Mage", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 22, stamina: 12, intelligence: 55, wisdom: 25, charisma: 35 },
  },
  {
    name: "Gorrak Stonehide",
    race: "Troll", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 52, agility: 16, stamina: 58, intelligence: 10, wisdom: 8, charisma: 6 },
  },
  {
    name: "Elindra",
    race: "Half Elf", class: "Troubador", archetype: "Scout", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 32, stamina: 18, intelligence: 20, wisdom: 16, charisma: 40 },
  },
  {
    name: "Vorrigan",
    race: "Human", class: "Paladin", archetype: "Fighter", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 42, agility: 18, stamina: 45, intelligence: 14, wisdom: 30, charisma: 22 },
  },
  {
    name: "Ssalika",
    race: "Iksar", class: "Monk", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 36, agility: 42, stamina: 32, intelligence: 16, wisdom: 22, charisma: 12 },
  },
  {
    name: "Pyrelia",
    race: "Erudite", class: "Coercer", archetype: "Mage", alignment: "Qeynos",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 60, wisdom: 30, charisma: 45 },
  },
  {
    name: "Thonk",
    race: "Halfling", class: "Dirge", archetype: "Scout", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 38, stamina: 14, intelligence: 16, wisdom: 14, charisma: 30 },
  },
  {
    name: "Rivendarax",
    race: "Dark Elf", class: "Wizard", archetype: "Mage", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 16, stamina: 14, intelligence: 62, wisdom: 22, charisma: 18 },
  },
  {
    name: "Gwendolyn Ashveil",
    race: "Human", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 16, stamina: 28, intelligence: 20, wisdom: 55, charisma: 28 },
  },
  {
    name: "Krix",
    race: "Gnome", class: "Warlock", archetype: "Mage", alignment: "Freeport",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 58, wisdom: 18, charisma: 22 },
  },
  {
    name: "Arzuhl",
    race: "Sarnak", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 55, agility: 24, stamina: 50, intelligence: 10, wisdom: 12, charisma: 10 },
  },
  {
    name: "Caladiel",
    race: "High Elf", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 24, stamina: 18, intelligence: 28, wisdom: 52, charisma: 30 },
  },
  {
    name: "Thurak",
    race: "Ogre", class: "Guardian", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 56, agility: 12, stamina: 58, intelligence: 8, wisdom: 10, charisma: 6 },
  },
  {
    name: "Whisperwind",
    race: "Fae", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 28, stamina: 14, intelligence: 18, wisdom: 46, charisma: 30 },
  },
  {
    name: "Daxaran",
    race: "Half Elf", class: "Swashbuckler", archetype: "Scout", alignment: "Freeport",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 22, agility: 48, stamina: 22, intelligence: 14, wisdom: 12, charisma: 28 },
  },
  {
    name: "Torgrath",
    race: "Troll", class: "Defiler", archetype: "Priest", alignment: "Freeport",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 22, agility: 16, stamina: 30, intelligence: 24, wisdom: 52, charisma: 8 },
  },
  {
    name: "Elindor Swiftblade",
    race: "Wood Elf", class: "Assassin", archetype: "Scout", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 22, agility: 55, stamina: 24, intelligence: 14, wisdom: 12, charisma: 18 },
  },
  {
    name: "Ironfist",
    race: "Dwarf", class: "Guardian", archetype: "Fighter", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 18, stamina: 52, intelligence: 10, wisdom: 14, charisma: 14 },
  },
  {
    name: "Maeloria",
    race: "Erudite", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 16, stamina: 22, intelligence: 35, wisdom: 60, charisma: 32 },
  },
  {
    name: "Razzik",
    race: "Iksar", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 22, stamina: 16, intelligence: 55, wisdom: 22, charisma: 12 },
  },
  {
    name: "Sunaria",
    race: "Kerra", class: "Troubador", archetype: "Scout", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 42, stamina: 20, intelligence: 18, wisdom: 14, charisma: 45 },
  },
  // ── New seeds 31–60 ──────────────────────────────────────────────────────────
  {
    name: "Draventhos",
    race: "Human", class: "Wizard", archetype: "Mage", alignment: "Freeport",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 14, stamina: 16, intelligence: 60, wisdom: 32, charisma: 22 },
  },
  {
    name: "Zizzix",
    race: "Ratonga", class: "Brigand", archetype: "Scout", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 52, stamina: 16, intelligence: 20, wisdom: 10, charisma: 28 },
  },
  {
    name: "Brondar",
    race: "Dwarf", class: "Berserker", archetype: "Fighter", alignment: "Qeynos",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 16, stamina: 54, intelligence: 8, wisdom: 12, charisma: 10 },
  },
  {
    name: "Lilyath",
    race: "Fae", class: "Illusionist", archetype: "Mage", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 26, stamina: 10, intelligence: 56, wisdom: 24, charisma: 40 },
  },
  {
    name: "Xanthrix",
    race: "Gnome", class: "Conjuror", archetype: "Mage", alignment: "Neutral",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 14, intelligence: 58, wisdom: 26, charisma: 24 },
  },
  {
    name: "Vadira",
    race: "Dark Elf", class: "Inquisitor", archetype: "Priest", alignment: "Freeport",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 18, stamina: 22, intelligence: 28, wisdom: 56, charisma: 22 },
  },
  {
    name: "Kraggash",
    race: "Troll", class: "Guardian", archetype: "Fighter", alignment: "Freeport",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 55, agility: 14, stamina: 60, intelligence: 8, wisdom: 10, charisma: 6 },
  },
  {
    name: "Aelindra",
    race: "High Elf", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 22, stamina: 16, intelligence: 26, wisdom: 54, charisma: 30 },
  },
  {
    name: "Snixpocket",
    race: "Ratonga", class: "Swashbuckler", archetype: "Scout", alignment: "Neutral",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 50, stamina: 18, intelligence: 16, wisdom: 10, charisma: 32 },
  },
  {
    name: "Quellorith",
    race: "Erudite", class: "Warlock", archetype: "Mage", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 12, stamina: 12, intelligence: 62, wisdom: 28, charisma: 20 },
  },
  {
    name: "Torash",
    race: "Iksar", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 48, agility: 24, stamina: 45, intelligence: 14, wisdom: 10, charisma: 8 },
  },
  {
    name: "Nimblewit",
    race: "Halfling", class: "Dirge", archetype: "Scout", alignment: "Neutral",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 40, stamina: 14, intelligence: 18, wisdom: 14, charisma: 36 },
  },
  {
    name: "Solvara",
    race: "Wood Elf", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 32, stamina: 16, intelligence: 20, wisdom: 48, charisma: 26 },
  },
  {
    name: "Graxmir",
    race: "Sarnak", class: "Bruiser", archetype: "Fighter", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 40, agility: 38, stamina: 44, intelligence: 10, wisdom: 12, charisma: 8 },
  },
  {
    name: "Pebbletop",
    race: "Halfling", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 26, stamina: 14, intelligence: 16, wisdom: 50, charisma: 28 },
  },
  {
    name: "Zolvara",
    race: "Arasai", class: "Wizard", archetype: "Mage", alignment: "Freeport",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 22, stamina: 12, intelligence: 60, wisdom: 20, charisma: 18 },
  },
  {
    name: "Hammerfist",
    race: "Ogre", class: "Bruiser", archetype: "Fighter", alignment: "Neutral",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 20, stamina: 56, intelligence: 8, wisdom: 10, charisma: 8 },
  },
  {
    name: "Faelindra",
    race: "Half Elf", class: "Ranger", archetype: "Scout", alignment: "Qeynos",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 22, agility: 50, stamina: 22, intelligence: 14, wisdom: 16, charisma: 18 },
  },
  {
    name: "Rikklix",
    race: "Ratonga", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 24, stamina: 12, intelligence: 56, wisdom: 22, charisma: 16 },
  },
  {
    name: "Storvald",
    race: "Barbarian", class: "Guardian", archetype: "Fighter", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 52, agility: 18, stamina: 54, intelligence: 10, wisdom: 14, charisma: 16 },
  },
  {
    name: "Krexxis",
    race: "Iksar", class: "Defiler", archetype: "Priest", alignment: "Freeport",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 18, stamina: 24, intelligence: 22, wisdom: 55, charisma: 10 },
  },
  {
    name: "Mirandel",
    race: "Human", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 16, stamina: 26, intelligence: 22, wisdom: 56, charisma: 26 },
  },
  {
    name: "Gildrix",
    race: "Gnome", class: "Coercer", archetype: "Mage", alignment: "Neutral",
    personality: "Scholarly",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 10, intelligence: 58, wisdom: 28, charisma: 42 },
  },
  {
    name: "Vexara",
    race: "Dark Elf", class: "Dirge", archetype: "Scout", alignment: "Freeport",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 44, stamina: 18, intelligence: 20, wisdom: 14, charisma: 36 },
  },
  {
    name: "Thundrak",
    race: "Barbarian", class: "Paladin", archetype: "Fighter", alignment: "Qeynos",
    personality: "Devout",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 44, agility: 18, stamina: 46, intelligence: 12, wisdom: 32, charisma: 20 },
  },
  {
    name: "Merrifax",
    race: "Froglok", class: "Mystic", archetype: "Priest", alignment: "Qeynos",
    personality: "Cautious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 30, stamina: 18, intelligence: 24, wisdom: 54, charisma: 24 },
  },
  {
    name: "Bolgrax",
    race: "Ogre", class: "Monk", archetype: "Fighter", alignment: "Neutral",
    personality: "Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 45, agility: 32, stamina: 46, intelligence: 10, wisdom: 18, charisma: 10 },
  },
  {
    name: "Aelixis",
    race: "Erudite", class: "Coercer", archetype: "Mage", alignment: "Neutral",
    personality: "Greedy",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 62, wisdom: 28, charisma: 44 },
  },
  {
    name: "Zythara",
    race: "Kerra", class: "Assassin", archetype: "Scout", alignment: "Freeport",
    personality: "Aggressive",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 24, agility: 56, stamina: 22, intelligence: 12, wisdom: 10, charisma: 16 },
  },

  // ── Seeds 61–78: Morning window (UTC 6–14) ────────────────────────────────
  {
    name: "Vaelindra",
    race: "Human", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "the Pious",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 20, stamina: 18, intelligence: 22, wisdom: 50, charisma: 26 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Grukkthar",
    race: "Ogre", class: "Bruiser", archetype: "Fighter", alignment: "Freeport",
    personality: "the Juggernaut",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 16, stamina: 54, intelligence: 8, wisdom: 9, charisma: 6 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Twixpip",
    race: "Gnome", class: "Wizard", archetype: "Mage", alignment: "Neutral",
    personality: "the Arcanist",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 12, intelligence: 60, wisdom: 24, charisma: 22 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Bronhilda",
    race: "Dwarf", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "the Holy Crusader",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 16, stamina: 24, intelligence: 20, wisdom: 52, charisma: 22 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Slix",
    race: "Ratonga", class: "Assassin", archetype: "Scout", alignment: "Freeport",
    personality: "the Loot-Goblin",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 52, stamina: 18, intelligence: 16, wisdom: 10, charisma: 20 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Lendral",
    race: "High Elf", class: "Ranger", archetype: "Scout", alignment: "Qeynos",
    personality: "the Pathfinder",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 46, stamina: 20, intelligence: 18, wisdom: 20, charisma: 16 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Zixxara",
    race: "Iksar", class: "Defiler", archetype: "Priest", alignment: "Freeport",
    personality: "the Faithful Servant",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 18, stamina: 20, intelligence: 24, wisdom: 54, charisma: 18 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Morindak",
    race: "Barbarian", class: "Guardian", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Defensive Wall",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 48, agility: 16, stamina: 55, intelligence: 9, wisdom: 12, charisma: 10 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Pyraxis",
    race: "Erudite", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "the Lore-Keeper",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 58, wisdom: 26, charisma: 20 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Gleepnik",
    race: "Gnome", class: "Illusionist", archetype: "Mage", alignment: "Neutral",
    personality: "the Wanderer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 56, wisdom: 22, charisma: 26 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Thundrax",
    race: "Sarnak", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Warlord",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 20, stamina: 46, intelligence: 16, wisdom: 12, charisma: 10 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Carabella",
    race: "Half Elf", class: "Dirge", archetype: "Scout", alignment: "Qeynos",
    personality: "the Chronicler",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 44, stamina: 18, intelligence: 20, wisdom: 14, charisma: 34 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Brixmor",
    race: "Troll", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "the Bloodletter",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 56, agility: 18, stamina: 52, intelligence: 8, wisdom: 8, charisma: 6 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Silvanel",
    race: "Wood Elf", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "the Patient Hunter",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 24, stamina: 16, intelligence: 20, wisdom: 48, charisma: 26 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Noxara",
    race: "Arasai", class: "Warlock", archetype: "Mage", alignment: "Freeport",
    personality: "the Profiteer",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 20, stamina: 12, intelligence: 54, wisdom: 22, charisma: 18 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Kettrick",
    race: "Human", class: "Monk", archetype: "Fighter", alignment: "Neutral",
    personality: "the Methodical",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 40, agility: 30, stamina: 44, intelligence: 14, wisdom: 18, charisma: 14 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Ysolde",
    race: "High Elf", class: "Coercer", archetype: "Mage", alignment: "Qeynos",
    personality: "the Academic",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 56, wisdom: 30, charisma: 34 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },
  {
    name: "Farrogk",
    race: "Ogre", class: "Guardian", archetype: "Fighter", alignment: "Neutral",
    personality: "the Steadfast",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 55, agility: 12, stamina: 58, intelligence: 8, wisdom: 10, charisma: 6 },
    activeHoursStart: 6, activeHoursEnd: 14,
  },

  // ── Seeds 79–96: Afternoon window (UTC 12–20) ─────────────────────────────
  {
    name: "Zirikka",
    race: "Iksar", class: "Brigand", archetype: "Scout", alignment: "Freeport",
    personality: "the Treasure-Seeker",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 50, stamina: 22, intelligence: 14, wisdom: 10, charisma: 18 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Fraelindra",
    race: "Fae", class: "Mystic", archetype: "Priest", alignment: "Qeynos",
    personality: "the Divine Champion",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 28, stamina: 16, intelligence: 22, wisdom: 48, charisma: 28 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Vorrax",
    race: "Dark Elf", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Ravager",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 48, agility: 24, stamina: 44, intelligence: 16, wisdom: 12, charisma: 10 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Zippet",
    race: "Halfling", class: "Swashbuckler", archetype: "Scout", alignment: "Neutral",
    personality: "the Fortune-Hunter",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 48, stamina: 20, intelligence: 14, wisdom: 12, charisma: 30 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Lorvaine",
    race: "Human", class: "Paladin", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Righteous",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 46, agility: 18, stamina: 48, intelligence: 12, wisdom: 30, charisma: 18 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Krixel",
    race: "Gnome", class: "Conjuror", archetype: "Mage", alignment: "Neutral",
    personality: "the Theory-Crafter",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 12, intelligence: 58, wisdom: 26, charisma: 22 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Tirasha",
    race: "Kerra", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "the Watchful",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 26, stamina: 18, intelligence: 22, wisdom: 46, charisma: 28 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Veldrak",
    race: "Barbarian", class: "Berserker", archetype: "Fighter", alignment: "Neutral",
    personality: "the Savage",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 54, agility: 22, stamina: 50, intelligence: 9, wisdom: 10, charisma: 12 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Xilara",
    race: "Dark Elf", class: "Dirge", archetype: "Scout", alignment: "Freeport",
    personality: "the Coin-Counter",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 46, stamina: 18, intelligence: 18, wisdom: 14, charisma: 28 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Brael",
    race: "Dwarf", class: "Monk", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Disciplined",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 42, agility: 28, stamina: 46, intelligence: 12, wisdom: 18, charisma: 12 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Quintessa",
    race: "Erudite", class: "Illusionist", archetype: "Mage", alignment: "Neutral",
    personality: "the Horizon-Chaser",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 12, intelligence: 58, wisdom: 28, charisma: 30 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Grimsoul",
    race: "Troll", class: "Defiler", archetype: "Priest", alignment: "Freeport",
    personality: "the Zealot",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 18, stamina: 22, intelligence: 22, wisdom: 52, charisma: 16 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Faerindra",
    race: "Wood Elf", class: "Ranger", archetype: "Scout", alignment: "Qeynos",
    personality: "the Trailblazer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 50, stamina: 22, intelligence: 16, wisdom: 18, charisma: 14 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Thaxar",
    race: "Sarnak", class: "Guardian", archetype: "Fighter", alignment: "Freeport",
    personality: "the Conqueror",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 18, stamina: 52, intelligence: 12, wisdom: 12, charisma: 10 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Pinwick",
    race: "Halfling", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "the Blessing-Seeker",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 22, stamina: 16, intelligence: 20, wisdom: 50, charisma: 28 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Krazak",
    race: "Ogre", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "the Berserker",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 60, agility: 14, stamina: 56, intelligence: 8, wisdom: 8, charisma: 6 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Vyndrel",
    race: "High Elf", class: "Wizard", archetype: "Mage", alignment: "Qeynos",
    personality: "the Sage",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 62, wisdom: 32, charisma: 20 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },
  {
    name: "Sorrisha",
    race: "Half Elf", class: "Troubador", archetype: "Scout", alignment: "Qeynos",
    personality: "the Cartographer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 44, stamina: 18, intelligence: 20, wisdom: 14, charisma: 36 },
    activeHoursStart: 12, activeHoursEnd: 20,
  },

  // ── Seeds 97–114: Evening window (UTC 17–1, wraps midnight) ──────────────
  {
    name: "Naxil",
    race: "Ratonga", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "the Greed-Incarnate",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 20, stamina: 12, intelligence: 56, wisdom: 20, charisma: 18 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Khaldrak",
    race: "Iksar", class: "Monk", archetype: "Fighter", alignment: "Freeport",
    personality: "the Fierce",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 42, agility: 32, stamina: 44, intelligence: 12, wisdom: 16, charisma: 12 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Yllindra",
    race: "Fae", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "the Covenant-Keeper",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 26, stamina: 14, intelligence: 20, wisdom: 50, charisma: 26 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Draekus",
    race: "Human", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Death-Seeker",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 48, agility: 20, stamina: 46, intelligence: 14, wisdom: 12, charisma: 12 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Lorrix",
    race: "Gnome", class: "Warlock", archetype: "Mage", alignment: "Neutral",
    personality: "the Wealth-Obsessed",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 60, wisdom: 24, charisma: 18 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Sylvara",
    race: "High Elf", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "the Consecrated",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 22, stamina: 14, intelligence: 24, wisdom: 52, charisma: 26 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Drakethorn",
    race: "Barbarian", class: "Guardian", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Iron-Fisted",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 52, agility: 16, stamina: 54, intelligence: 9, wisdom: 12, charisma: 10 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Milixal",
    race: "Ratonga", class: "Brigand", archetype: "Scout", alignment: "Freeport",
    personality: "the Plunderer",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 52, stamina: 18, intelligence: 14, wisdom: 10, charisma: 22 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Valandrin",
    race: "Erudite", class: "Coercer", archetype: "Mage", alignment: "Neutral",
    personality: "the Philosopher",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 60, wisdom: 28, charisma: 28 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Gruknar",
    race: "Troll", class: "Bruiser", archetype: "Fighter", alignment: "Freeport",
    personality: "the Brutal",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 56, agility: 16, stamina: 52, intelligence: 8, wisdom: 8, charisma: 6 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Kaelindra",
    race: "Wood Elf", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "the Vigilant",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 24, stamina: 16, intelligence: 20, wisdom: 50, charisma: 24 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Drexxus",
    race: "Dark Elf", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "the Mystery-Solver",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 58, wisdom: 22, charisma: 16 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Smirkle",
    race: "Halfling", class: "Dirge", archetype: "Scout", alignment: "Neutral",
    personality: "the Nomad",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 46, stamina: 18, intelligence: 16, wisdom: 12, charisma: 30 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Vorthas",
    race: "Human", class: "Berserker", archetype: "Fighter", alignment: "Neutral",
    personality: "the Warmonger",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 22, stamina: 48, intelligence: 10, wisdom: 12, charisma: 12 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Sylindrix",
    race: "Arasai", class: "Illusionist", archetype: "Mage", alignment: "Freeport",
    personality: "the Curiosity-Driven",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 20, stamina: 12, intelligence: 56, wisdom: 22, charisma: 28 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Borast",
    race: "Dwarf", class: "Guardian", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Enduring",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 46, agility: 16, stamina: 54, intelligence: 10, wisdom: 14, charisma: 10 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Xanzira",
    race: "Iksar", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Oppressor",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 22, stamina: 46, intelligence: 14, wisdom: 12, charisma: 8 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },
  {
    name: "Froglox",
    race: "Froglok", class: "Mystic", archetype: "Priest", alignment: "Qeynos",
    personality: "the Humble Servant",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 26, stamina: 16, intelligence: 22, wisdom: 52, charisma: 24 },
    activeHoursStart: 17, activeHoursEnd: 1,
  },

  // ── Seeds 115–132: Night window (UTC 21–5, wraps midnight) ────────────────
  {
    name: "Melindrix",
    race: "Half Elf", class: "Troubador", archetype: "Scout", alignment: "Qeynos",
    personality: "the Relic-Hunter",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 44, stamina: 18, intelligence: 22, wisdom: 14, charisma: 36 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Kraxar",
    race: "Sarnak", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "the Decimator",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 52, agility: 20, stamina: 50, intelligence: 10, wisdom: 10, charisma: 10 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Yvelindra",
    race: "Fae", class: "Fury", archetype: "Priest", alignment: "Qeynos",
    personality: "the Grace-Embodied",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 28, stamina: 14, intelligence: 22, wisdom: 48, charisma: 30 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Trixa",
    race: "Ratonga", class: "Swashbuckler", archetype: "Scout", alignment: "Neutral",
    personality: "the Opportunist",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 50, stamina: 18, intelligence: 14, wisdom: 10, charisma: 26 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Valdrak",
    race: "Ogre", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Tyrant",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 14, stamina: 52, intelligence: 14, wisdom: 10, charisma: 8 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Aerindra",
    race: "High Elf", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "the Devoted",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 18, stamina: 18, intelligence: 22, wisdom: 54, charisma: 24 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Grixmaw",
    race: "Troll", class: "Shadowknight", archetype: "Fighter", alignment: "Freeport",
    personality: "the Annihilator",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 54, agility: 16, stamina: 50, intelligence: 12, wisdom: 10, charisma: 8 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Pezzrix",
    race: "Gnome", class: "Necromancer", archetype: "Mage", alignment: "Freeport",
    personality: "the Avaricious",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 58, wisdom: 20, charisma: 18 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Vaelorna",
    race: "Human", class: "Warden", archetype: "Priest", alignment: "Neutral",
    personality: "the Reserved",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 20, stamina: 18, intelligence: 20, wisdom: 50, charisma: 24 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Thuknar",
    race: "Ogre", class: "Bruiser", archetype: "Fighter", alignment: "Freeport",
    personality: "the Skullcrusher",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 14, stamina: 56, intelligence: 8, wisdom: 8, charisma: 6 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Naeris",
    race: "Dark Elf", class: "Wizard", archetype: "Mage", alignment: "Freeport",
    personality: "the Forbidden-Knowledge Seeker",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 12, intelligence: 62, wisdom: 28, charisma: 16 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Fizzwick",
    race: "Gnome", class: "Illusionist", archetype: "Mage", alignment: "Neutral",
    personality: "the World-Explorer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 56, wisdom: 24, charisma: 26 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Kaldrath",
    race: "Iksar", class: "Defiler", archetype: "Priest", alignment: "Freeport",
    personality: "the Temple Guardian",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 18, stamina: 20, intelligence: 22, wisdom: 52, charisma: 18 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Sylorn",
    race: "Wood Elf", class: "Assassin", archetype: "Scout", alignment: "Qeynos",
    personality: "the Schemer",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 52, stamina: 20, intelligence: 14, wisdom: 10, charisma: 18 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Threndar",
    race: "Barbarian", class: "Berserker", archetype: "Fighter", alignment: "Neutral",
    personality: "the Unstoppable",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 56, agility: 18, stamina: 52, intelligence: 9, wisdom: 10, charisma: 12 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Elindrix",
    race: "High Elf", class: "Coercer", archetype: "Mage", alignment: "Qeynos",
    personality: "the Encyclopedic",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 60, wisdom: 30, charisma: 32 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Wramble",
    race: "Halfling", class: "Swashbuckler", archetype: "Scout", alignment: "Qeynos",
    personality: "the Boundless",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 46, stamina: 18, intelligence: 14, wisdom: 12, charisma: 30 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },
  {
    name: "Kruxal",
    race: "Sarnak", class: "Guardian", archetype: "Fighter", alignment: "Freeport",
    personality: "the Stalwart",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 16, stamina: 54, intelligence: 10, wisdom: 12, charisma: 10 },
    activeHoursStart: 21, activeHoursEnd: 5,
  },

  // ── Seeds 133–150: Late Afternoon window (UTC 13–21) ──────────────────────
  {
    name: "Sylindrel",
    race: "High Elf", class: "Warden", archetype: "Priest", alignment: "Qeynos",
    personality: "the Prayer-Guided",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 22, stamina: 16, intelligence: 24, wisdom: 52, charisma: 26 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Rathkrak",
    race: "Dwarf", class: "Berserker", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Battle-Mad",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 50, agility: 20, stamina: 48, intelligence: 10, wisdom: 12, charisma: 10 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Vexindra",
    race: "Dark Elf", class: "Dirge", archetype: "Scout", alignment: "Freeport",
    personality: "the Market-Watcher",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 46, stamina: 18, intelligence: 18, wisdom: 14, charisma: 28 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Borrigan",
    race: "Human", class: "Paladin", archetype: "Fighter", alignment: "Qeynos",
    personality: "the Holy Warrior",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 46, agility: 18, stamina: 48, intelligence: 12, wisdom: 32, charisma: 18 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Nikkrix",
    race: "Ratonga", class: "Assassin", archetype: "Scout", alignment: "Freeport",
    personality: "the Cut-Throat",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 18, agility: 54, stamina: 18, intelligence: 14, wisdom: 10, charisma: 18 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Aelixar",
    race: "Erudite", class: "Wizard", archetype: "Mage", alignment: "Neutral",
    personality: "the Runic-Scholar",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 62, wisdom: 30, charisma: 22 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Miranna",
    race: "Half Elf", class: "Mystic", archetype: "Priest", alignment: "Qeynos",
    personality: "the Serene Defender",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 14, agility: 22, stamina: 18, intelligence: 22, wisdom: 50, charisma: 28 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Zolvrix",
    race: "Iksar", class: "Monk", archetype: "Fighter", alignment: "Freeport",
    personality: "the Relentless",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 42, agility: 30, stamina: 44, intelligence: 12, wisdom: 14, charisma: 12 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Thamble",
    race: "Halfling", class: "Brigand", archetype: "Scout", alignment: "Neutral",
    personality: "the Bargain-Hunter",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 16, agility: 48, stamina: 18, intelligence: 16, wisdom: 12, charisma: 28 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Xaerindra",
    race: "Arasai", class: "Warlock", archetype: "Mage", alignment: "Freeport",
    personality: "the Lore-Driven",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 18, stamina: 12, intelligence: 58, wisdom: 22, charisma: 20 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Dorthak",
    race: "Troll", class: "Guardian", archetype: "Fighter", alignment: "Freeport",
    personality: "the Iron Guard",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 54, agility: 14, stamina: 56, intelligence: 8, wisdom: 10, charisma: 8 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Yloriel",
    race: "Wood Elf", class: "Ranger", archetype: "Scout", alignment: "Qeynos",
    personality: "the Far-Traveller",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 20, agility: 50, stamina: 22, intelligence: 16, wisdom: 18, charisma: 14 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Prixmok",
    race: "Gnome", class: "Coercer", archetype: "Mage", alignment: "Neutral",
    personality: "the Intellectual",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 16, stamina: 12, intelligence: 60, wisdom: 28, charisma: 26 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Sarnakkar",
    race: "Sarnak", class: "Berserker", archetype: "Fighter", alignment: "Freeport",
    personality: "the Vengeance-Driven",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 52, agility: 20, stamina: 50, intelligence: 10, wisdom: 10, charisma: 10 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Florvaine",
    race: "Fae", class: "Templar", archetype: "Priest", alignment: "Qeynos",
    personality: "the Ordained",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 10, agility: 26, stamina: 16, intelligence: 22, wisdom: 50, charisma: 28 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Grommex",
    race: "Ogre", class: "Bruiser", archetype: "Fighter", alignment: "Freeport",
    personality: "the Gladiator",
    level: 1, xp: 0, gold: 0, zone: "Commonlands",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 58, agility: 16, stamina: 54, intelligence: 8, wisdom: 8, charisma: 6 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Raelindra",
    race: "High Elf", class: "Inquisitor", archetype: "Priest", alignment: "Qeynos",
    personality: "the Faith-Bound",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 12, agility: 20, stamina: 18, intelligence: 26, wisdom: 54, charisma: 22 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
  {
    name: "Morvaxis",
    race: "Human", class: "Wizard", archetype: "Mage", alignment: "Neutral",
    personality: "the Theorist",
    level: 1, xp: 0, gold: 0, zone: "Antonica",
    killCount: 0, deathCount: 0, bossKills: 0, totalGoldEarned: 0, totalGoldSpent: 0,
    stats: { strength: 8, agility: 14, stamina: 12, intelligence: 62, wisdom: 28, charisma: 20 },
    activeHoursStart: 13, activeHoursEnd: 21,
  },
];
