/**
 * Ghost Personality Catalog — 300 named personalities across 6 behavioral archetypes.
 *
 * Each personality has:
 *   - id      — stable slug used for lookups
 *   - label   — display name shown in the UI (e.g. "the Berserker")
 *   - archetype — one of the 6 core behavioral archetypes that drives simulation logic
 *
 * Archetypes map to PersonalityConfig in ghostSimulator.ts:
 *   Aggressive | Cautious | Explorer | Greedy | Scholarly | Devout
 *
 * 50 personalities per archetype = 300 total.
 */

export type GhostPersonality = "Aggressive" | "Cautious" | "Explorer" | "Greedy" | "Scholarly" | "Devout";

export interface GhostPersonalityDef {
  id: string;
  label: string;
  archetype: GhostPersonality;
}

// ─── Aggressive (50) — high boss rate, brutal events, reckless combat ─────────
const AGGRESSIVE: GhostPersonalityDef[] = [
  { id: "the_berserker",          label: "the Berserker",          archetype: "Aggressive" },
  { id: "the_bloodletter",        label: "the Bloodletter",        archetype: "Aggressive" },
  { id: "the_warlord",            label: "the Warlord",            archetype: "Aggressive" },
  { id: "the_devastator",         label: "the Devastator",         archetype: "Aggressive" },
  { id: "the_unstoppable",        label: "the Unstoppable",        archetype: "Aggressive" },
  { id: "the_savage",             label: "the Savage",             archetype: "Aggressive" },
  { id: "the_relentless",         label: "the Relentless",         archetype: "Aggressive" },
  { id: "the_bloodthirsty",       label: "the Bloodthirsty",       archetype: "Aggressive" },
  { id: "the_destroyer",          label: "the Destroyer",          archetype: "Aggressive" },
  { id: "the_merciless",          label: "the Merciless",          archetype: "Aggressive" },
  { id: "the_fierce",             label: "the Fierce",             archetype: "Aggressive" },
  { id: "the_furious",            label: "the Furious",            archetype: "Aggressive" },
  { id: "the_ruthless",           label: "the Ruthless",           archetype: "Aggressive" },
  { id: "the_dreadful",           label: "the Dreadful",           archetype: "Aggressive" },
  { id: "the_brutal",             label: "the Brutal",             archetype: "Aggressive" },
  { id: "the_ferocious",          label: "the Ferocious",          archetype: "Aggressive" },
  { id: "the_unhinged",           label: "the Unhinged",           archetype: "Aggressive" },
  { id: "the_warmonger",          label: "the Warmonger",          archetype: "Aggressive" },
  { id: "the_rampager",           label: "the Rampager",           archetype: "Aggressive" },
  { id: "the_skullcrusher",       label: "the Skullcrusher",       archetype: "Aggressive" },
  { id: "the_iron_fisted",        label: "the Iron-Fisted",        archetype: "Aggressive" },
  { id: "the_wrathful",           label: "the Wrathful",           archetype: "Aggressive" },
  { id: "the_battle_mad",         label: "the Battle-Mad",         archetype: "Aggressive" },
  { id: "the_death_seeker",       label: "the Death-Seeker",       archetype: "Aggressive" },
  { id: "the_vengeance_driven",   label: "the Vengeance-Driven",   archetype: "Aggressive" },
  { id: "the_rage_filled",        label: "the Rage-Filled",        archetype: "Aggressive" },
  { id: "the_murder_minded",      label: "the Murder-Minded",      archetype: "Aggressive" },
  { id: "the_sword_hungry",       label: "the Sword-Hungry",       archetype: "Aggressive" },
  { id: "the_headstrong",         label: "the Headstrong",         archetype: "Aggressive" },
  { id: "the_hothead",            label: "the Hothead",            archetype: "Aggressive" },
  { id: "the_reckless_combatant", label: "the Reckless Combatant", archetype: "Aggressive" },
  { id: "the_gladiator",          label: "the Gladiator",          archetype: "Aggressive" },
  { id: "the_juggernaut",         label: "the Juggernaut",         archetype: "Aggressive" },
  { id: "the_blood_crazed",       label: "the Blood-Crazed",       archetype: "Aggressive" },
  { id: "the_conqueror",          label: "the Conqueror",          archetype: "Aggressive" },
  { id: "the_tyrant",             label: "the Tyrant",             archetype: "Aggressive" },
  { id: "the_ravager",            label: "the Ravager",            archetype: "Aggressive" },
  { id: "the_vanquisher",         label: "the Vanquisher",         archetype: "Aggressive" },
  { id: "the_decimator",          label: "the Decimator",          archetype: "Aggressive" },
  { id: "the_annihilator",        label: "the Annihilator",        archetype: "Aggressive" },
  { id: "the_oppressor",          label: "the Oppressor",          archetype: "Aggressive" },
  { id: "the_combat_addict",      label: "the Combat-Addict",      archetype: "Aggressive" },
  { id: "the_battle_hungry",      label: "the Battle-Hungry",      archetype: "Aggressive" },
  { id: "the_aggressor",          label: "the Aggressor",          archetype: "Aggressive" },
  { id: "the_slayer",             label: "the Slayer",             archetype: "Aggressive" },
  { id: "the_champion_of_war",    label: "the Champion of War",    archetype: "Aggressive" },
  { id: "the_war_hardened",       label: "the War-Hardened",       archetype: "Aggressive" },
  { id: "the_blade_hungry",       label: "the Blade-Hungry",       archetype: "Aggressive" },
  { id: "the_undying_fury",       label: "the Undying Fury",       archetype: "Aggressive" },
  { id: "the_bringer_of_ruin",    label: "the Bringer of Ruin",    archetype: "Aggressive" },
];

// ─── Cautious (50) — low boss rate, defensive, patient, lingers safely ────────
const CAUTIOUS: GhostPersonalityDef[] = [
  { id: "the_careful_strategist",    label: "the Careful Strategist",    archetype: "Cautious" },
  { id: "the_patient_hunter",        label: "the Patient Hunter",        archetype: "Cautious" },
  { id: "the_defensive_wall",        label: "the Defensive Wall",        archetype: "Cautious" },
  { id: "the_methodical",            label: "the Methodical",            archetype: "Cautious" },
  { id: "the_calculating",           label: "the Calculating",           archetype: "Cautious" },
  { id: "the_risk_averse",           label: "the Risk-Averse",           archetype: "Cautious" },
  { id: "the_steadfast",             label: "the Steadfast",             archetype: "Cautious" },
  { id: "the_measured",              label: "the Measured",              archetype: "Cautious" },
  { id: "the_prudent",               label: "the Prudent",               archetype: "Cautious" },
  { id: "the_watchful",              label: "the Watchful",              archetype: "Cautious" },
  { id: "the_shield_bearer",         label: "the Shield-Bearer",         archetype: "Cautious" },
  { id: "the_survivor",              label: "the Survivor",              archetype: "Cautious" },
  { id: "the_enduring",              label: "the Enduring",              archetype: "Cautious" },
  { id: "the_slow_and_steady",       label: "the Slow-and-Steady",       archetype: "Cautious" },
  { id: "the_prepared",              label: "the Prepared",              archetype: "Cautious" },
  { id: "the_wary",                  label: "the Wary",                  archetype: "Cautious" },
  { id: "the_vigilant",              label: "the Vigilant",              archetype: "Cautious" },
  { id: "the_reserved",              label: "the Reserved",              archetype: "Cautious" },
  { id: "the_tactical",              label: "the Tactical",              archetype: "Cautious" },
  { id: "the_controlled",            label: "the Controlled",            archetype: "Cautious" },
  { id: "the_planner",               label: "the Planner",               archetype: "Cautious" },
  { id: "the_deliberate",            label: "the Deliberate",            archetype: "Cautious" },
  { id: "the_disciplined",           label: "the Disciplined",           archetype: "Cautious" },
  { id: "the_serene_defender",       label: "the Serene Defender",       archetype: "Cautious" },
  { id: "the_well_protected",        label: "the Well-Protected",        archetype: "Cautious" },
  { id: "the_careful_fighter",       label: "the Careful Fighter",       archetype: "Cautious" },
  { id: "the_unhurried",             label: "the Unhurried",             archetype: "Cautious" },
  { id: "the_long_game_player",      label: "the Long-Game Player",      archetype: "Cautious" },
  { id: "the_stalwart",              label: "the Stalwart",              archetype: "Cautious" },
  { id: "the_iron_guard",            label: "the Iron Guard",            archetype: "Cautious" },
  { id: "the_conservative",          label: "the Conservative",          archetype: "Cautious" },
  { id: "the_meticulous",            label: "the Meticulous",            archetype: "Cautious" },
  { id: "the_over_prepared",         label: "the Over-Prepared",         archetype: "Cautious" },
  { id: "the_safety_first",          label: "the Safety-First",          archetype: "Cautious" },
  { id: "the_measured_blade",        label: "the Measured Blade",        archetype: "Cautious" },
  { id: "the_analytical",            label: "the Analytical",            archetype: "Cautious" },
  { id: "the_thoughtful",            label: "the Thoughtful",            archetype: "Cautious" },
  { id: "the_precise",               label: "the Precise",               archetype: "Cautious" },
  { id: "the_patient_warrior",       label: "the Patient Warrior",       archetype: "Cautious" },
  { id: "the_cautious_mage",         label: "the Cautious Mage",         archetype: "Cautious" },
  { id: "the_shield_first",          label: "the Shield-First",          archetype: "Cautious" },
  { id: "the_careful_scout",         label: "the Careful Scout",         archetype: "Cautious" },
  { id: "the_composed",              label: "the Composed",              archetype: "Cautious" },
  { id: "the_battle_tested_defender",label: "the Battle-Tested Defender",archetype: "Cautious" },
  { id: "the_resilient",             label: "the Resilient",             archetype: "Cautious" },
  { id: "the_unflappable",           label: "the Unflappable",           archetype: "Cautious" },
  { id: "the_imperturbable",         label: "the Imperturbable",         archetype: "Cautious" },
  { id: "the_calculated_striker",    label: "the Calculated Striker",    archetype: "Cautious" },
  { id: "the_never_rushed",          label: "the Never-Rushed",          archetype: "Cautious" },
  { id: "the_wise_survivor",         label: "the Wise Survivor",         archetype: "Cautious" },
];

// ─── Explorer (50) — frequent zone travel, discovery events, curiosity ────────
const EXPLORER: GhostPersonalityDef[] = [
  { id: "the_wanderer",                   label: "the Wanderer",                   archetype: "Explorer" },
  { id: "the_pathfinder",                 label: "the Pathfinder",                 archetype: "Explorer" },
  { id: "the_cartographer",               label: "the Cartographer",               archetype: "Explorer" },
  { id: "the_horizon_chaser",             label: "the Horizon-Chaser",             archetype: "Explorer" },
  { id: "the_rambler",                    label: "the Rambler",                    archetype: "Explorer" },
  { id: "the_adventurous",                label: "the Adventurous",                archetype: "Explorer" },
  { id: "the_discoverer",                 label: "the Discoverer",                 archetype: "Explorer" },
  { id: "the_zone_hopper",                label: "the Zone-Hopper",                archetype: "Explorer" },
  { id: "the_trailblazer",                label: "the Trailblazer",                archetype: "Explorer" },
  { id: "the_pioneer",                    label: "the Pioneer",                    archetype: "Explorer" },
  { id: "the_frontier_seeker",            label: "the Frontier-Seeker",            archetype: "Explorer" },
  { id: "the_far_traveller",              label: "the Far-Traveller",              archetype: "Explorer" },
  { id: "the_restless_spirit",            label: "the Restless Spirit",            archetype: "Explorer" },
  { id: "the_nomad",                      label: "the Nomad",                      archetype: "Explorer" },
  { id: "the_curiosity_driven",           label: "the Curiosity-Driven",           archetype: "Explorer" },
  { id: "the_map_maker",                  label: "the Map-Maker",                  archetype: "Explorer" },
  { id: "the_world_explorer",             label: "the World-Explorer",             archetype: "Explorer" },
  { id: "the_boundless",                  label: "the Boundless",                  archetype: "Explorer" },
  { id: "the_horizon_gazer",              label: "the Horizon Gazer",              archetype: "Explorer" },
  { id: "the_secret_hunter",             label: "the Secret-Hunter",             archetype: "Explorer" },
  { id: "the_hidden_path_walker",         label: "the Hidden-Path Walker",         archetype: "Explorer" },
  { id: "the_wilderness_lover",           label: "the Wilderness-Lover",           archetype: "Explorer" },
  { id: "the_intrepid",                   label: "the Intrepid",                   archetype: "Explorer" },
  { id: "the_wide_eyed_wanderer",         label: "the Wide-Eyed Wanderer",         archetype: "Explorer" },
  { id: "the_relentless_explorer",        label: "the Relentless Explorer",        archetype: "Explorer" },
  { id: "the_rugged_traveller",           label: "the Rugged Traveller",           archetype: "Explorer" },
  { id: "the_first_footstep",             label: "the First-Footstep",             archetype: "Explorer" },
  { id: "the_moving_target",              label: "the Moving Target",              archetype: "Explorer" },
  { id: "the_never_settles",              label: "the Never-Settles",              archetype: "Explorer" },
  { id: "the_far_ranging",                label: "the Far-Ranging",                archetype: "Explorer" },
  { id: "the_zone_conqueror",             label: "the Zone-Mapper",                archetype: "Explorer" },
  { id: "the_undiscovered_country_seeker",label: "the Undiscovered-Country Seeker",archetype: "Explorer" },
  { id: "the_world_weary_wanderer",       label: "the World-Weary Wanderer",       archetype: "Explorer" },
  { id: "the_destination_unknown",        label: "the Destination-Unknown",        archetype: "Explorer" },
  { id: "the_map_collector",              label: "the Map-Collector",              archetype: "Explorer" },
  { id: "the_boundary_pusher",            label: "the Boundary-Pusher",            archetype: "Explorer" },
  { id: "the_cross_zone_traveller",       label: "the Cross-Zone Traveller",       archetype: "Explorer" },
  { id: "the_always_exploring",           label: "the Always-Exploring",           archetype: "Explorer" },
  { id: "the_untamed_wanderer",           label: "the Untamed Wanderer",           archetype: "Explorer" },
  { id: "the_restless_adventurer",        label: "the Restless Adventurer",        archetype: "Explorer" },
  { id: "the_world_chronicler",           label: "the World-Chronicler",           archetype: "Explorer" },
  { id: "the_landmark_seeker",            label: "the Landmark-Seeker",            archetype: "Explorer" },
  { id: "the_uncharted_territory_expert", label: "the Uncharted-Territory Expert", archetype: "Explorer" },
  { id: "the_expedition_ready",           label: "the Expedition-Ready",           archetype: "Explorer" },
  { id: "the_wilderness_hardened",        label: "the Wilderness-Hardened",        archetype: "Explorer" },
  { id: "the_footprint_leaver",           label: "the Footprint-Leaver",           archetype: "Explorer" },
  { id: "the_curiosity_led",              label: "the Curiosity-Led",              archetype: "Explorer" },
  { id: "the_new_world_seeker",           label: "the New-World Seeker",           archetype: "Explorer" },
  { id: "the_roadless_traveller",         label: "the Roadless-Traveller",         archetype: "Explorer" },
  { id: "the_perpetual_journeyman",       label: "the Perpetual Journeyman",       archetype: "Explorer" },
];

// ─── Greedy (50) — high loot chance, hoards gold, economically aggressive ─────
const GREEDY: GhostPersonalityDef[] = [
  { id: "the_gold_hoarder",           label: "the Gold-Hoarder",           archetype: "Greedy" },
  { id: "the_treasure_seeker",        label: "the Treasure-Seeker",        archetype: "Greedy" },
  { id: "the_coin_counter",           label: "the Coin-Counter",           archetype: "Greedy" },
  { id: "the_loot_monger",            label: "the Loot-Monger",            archetype: "Greedy" },
  { id: "the_miser",                  label: "the Miser",                  archetype: "Greedy" },
  { id: "the_fortune_hunter",         label: "the Fortune-Hunter",         archetype: "Greedy" },
  { id: "the_profiteer",              label: "the Profiteer",              archetype: "Greedy" },
  { id: "the_mercenary",              label: "the Mercenary",              archetype: "Greedy" },
  { id: "the_cut_throat",             label: "the Cut-Throat",             archetype: "Greedy" },
  { id: "the_bargain_hunter",         label: "the Bargain-Hunter",         archetype: "Greedy" },
  { id: "the_wealth_obsessed",        label: "the Wealth-Obsessed",        archetype: "Greedy" },
  { id: "the_gold_fever_patient",     label: "the Gold-Fever Patient",     archetype: "Greedy" },
  { id: "the_avaricious",             label: "the Avaricious",             archetype: "Greedy" },
  { id: "the_penny_pincher",          label: "the Penny-Pincher",          archetype: "Greedy" },
  { id: "the_loot_goblin",            label: "the Loot-Goblin",            archetype: "Greedy" },
  { id: "the_coin_hungry",            label: "the Coin-Hungry",            archetype: "Greedy" },
  { id: "the_treasure_obsessed",      label: "the Treasure-Obsessed",      archetype: "Greedy" },
  { id: "the_greed_incarnate",        label: "the Greed-Incarnate",        archetype: "Greedy" },
  { id: "the_coin_collector",         label: "the Coin-Collector",         archetype: "Greedy" },
  { id: "the_fortune_chaser",         label: "the Fortune-Chaser",         archetype: "Greedy" },
  { id: "the_plunderer",              label: "the Plunderer",              archetype: "Greedy" },
  { id: "the_pillager",               label: "the Pillager",               archetype: "Greedy" },
  { id: "the_never_satisfied",        label: "the Never-Satisfied",        archetype: "Greedy" },
  { id: "the_gold_thirsty",           label: "the Gold-Thirsty",           archetype: "Greedy" },
  { id: "the_market_watcher",         label: "the Market-Watcher",         archetype: "Greedy" },
  { id: "the_opportunist",            label: "the Opportunist",            archetype: "Greedy" },
  { id: "the_schemer",                label: "the Schemer",                archetype: "Greedy" },
  { id: "the_self_serving",           label: "the Self-Serving",           archetype: "Greedy" },
  { id: "the_always_counting",        label: "the Always-Counting",        archetype: "Greedy" },
  { id: "the_wealth_maximizer",       label: "the Wealth-Maximizer",       archetype: "Greedy" },
  { id: "the_loot_calculator",        label: "the Loot-Calculator",        archetype: "Greedy" },
  { id: "the_drop_rate_optimizer",    label: "the Drop-Rate-Optimizer",    archetype: "Greedy" },
  { id: "the_investment_minded",      label: "the Investment-Minded",      archetype: "Greedy" },
  { id: "the_hoarder_supreme",        label: "the Hoarder Supreme",        archetype: "Greedy" },
  { id: "the_dragon_hoard_aspirant",  label: "the Dragon-Hoard Aspirant",  archetype: "Greedy" },
  { id: "the_merchant_at_heart",      label: "the Merchant-at-Heart",      archetype: "Greedy" },
  { id: "the_gold_seeker",            label: "the Gold-Seeker",            archetype: "Greedy" },
  { id: "the_coin_obsessed",          label: "the Coin-Obsessed",          archetype: "Greedy" },
  { id: "the_wealth_accumulator",     label: "the Wealth-Accumulator",     archetype: "Greedy" },
  { id: "the_loot_driven",            label: "the Loot-Driven",            archetype: "Greedy" },
  { id: "the_gold_thief",             label: "the Gold-Thief",             archetype: "Greedy" },
  { id: "the_treasure_sniffing",      label: "the Treasure-Sniffing",      archetype: "Greedy" },
  { id: "the_never_enough",           label: "the Never-Enough",           archetype: "Greedy" },
  { id: "the_profit_minded",          label: "the Profit-Minded",          archetype: "Greedy" },
  { id: "the_acquisition_hunter",     label: "the Acquisition-Hunter",     archetype: "Greedy" },
  { id: "the_bottom_line_focused",    label: "the Bottom-Line Focused",    archetype: "Greedy" },
  { id: "the_net_worth_tracker",      label: "the Net-Worth-Tracker",      archetype: "Greedy" },
  { id: "the_market_manipulator",     label: "the Market-Manipulator",     archetype: "Greedy" },
  { id: "the_prize_seeker",           label: "the Prize-Seeker",           archetype: "Greedy" },
  { id: "the_wealth_commanded",       label: "the Wealth-Commanded",       archetype: "Greedy" },
];

// ─── Scholarly (50) — lore events, texts, adornments, buys materials ──────────
const SCHOLARLY: GhostPersonalityDef[] = [
  { id: "the_arcanist",                  label: "the Arcanist",                  archetype: "Scholarly" },
  { id: "the_lore_keeper",               label: "the Lore-Keeper",               archetype: "Scholarly" },
  { id: "the_sage",                      label: "the Sage",                      archetype: "Scholarly" },
  { id: "the_researcher",                label: "the Researcher",                archetype: "Scholarly" },
  { id: "the_chronicler",                label: "the Chronicler",                archetype: "Scholarly" },
  { id: "the_scholar",                   label: "the Scholar",                   archetype: "Scholarly" },
  { id: "the_ink_stained",               label: "the Ink-Stained",               archetype: "Scholarly" },
  { id: "the_runic_scholar",             label: "the Runic-Scholar",             archetype: "Scholarly" },
  { id: "the_lore_master",               label: "the Lore-Master",               archetype: "Scholarly" },
  { id: "the_bestiary_writer",           label: "the Bestiary-Writer",           archetype: "Scholarly" },
  { id: "the_theory_crafter",            label: "the Theory-Crafter",            archetype: "Scholarly" },
  { id: "the_magical_theorist",          label: "the Magical-Theorist",          archetype: "Scholarly" },
  { id: "the_ancient_text_lover",        label: "the Ancient-Text Lover",        archetype: "Scholarly" },
  { id: "the_tome_collector",            label: "the Tome-Collector",            archetype: "Scholarly" },
  { id: "the_rune_reader",               label: "the Rune-Reader",               archetype: "Scholarly" },
  { id: "the_artifact_seeker",           label: "the Artifact-Seeker",           archetype: "Scholarly" },
  { id: "the_knowledge_hungry",          label: "the Knowledge-Hungry",          archetype: "Scholarly" },
  { id: "the_wisdom_seeker",             label: "the Wisdom-Seeker",             archetype: "Scholarly" },
  { id: "the_academic",                  label: "the Academic",                  archetype: "Scholarly" },
  { id: "the_intellectual",              label: "the Intellectual",              archetype: "Scholarly" },
  { id: "the_lore_driven",               label: "the Lore-Driven",               archetype: "Scholarly" },
  { id: "the_research_minded",           label: "the Research-Minded",           archetype: "Scholarly" },
  { id: "the_field_researcher",          label: "the Field-Researcher",          archetype: "Scholarly" },
  { id: "the_encyclopedic",              label: "the Encyclopedic",              archetype: "Scholarly" },
  { id: "the_pattern_finder",            label: "the Pattern-Finder",            archetype: "Scholarly" },
  { id: "the_hypothesis_tester",         label: "the Hypothesis-Tester",         archetype: "Scholarly" },
  { id: "the_note_taker",                label: "the Note-Taker",                archetype: "Scholarly" },
  { id: "the_archivist",                 label: "the Archivist",                 archetype: "Scholarly" },
  { id: "the_historian",                 label: "the Historian",                 archetype: "Scholarly" },
  { id: "the_philosopher",               label: "the Philosopher",               archetype: "Scholarly" },
  { id: "the_mystery_solver",            label: "the Mystery-Solver",            archetype: "Scholarly" },
  { id: "the_antiquarian",               label: "the Antiquarian",               archetype: "Scholarly" },
  { id: "the_magical_naturalist",        label: "the Magical-Naturalist",        archetype: "Scholarly" },
  { id: "the_taxonomist",                label: "the Taxonomist",                archetype: "Scholarly" },
  { id: "the_relic_hunter",              label: "the Relic-Hunter",              archetype: "Scholarly" },
  { id: "the_forbidden_knowledge_seeker",label: "the Forbidden-Knowledge Seeker",archetype: "Scholarly" },
  { id: "the_dungeon_documenter",        label: "the Dungeon-Documenter",        archetype: "Scholarly" },
  { id: "the_expedition_scholar",        label: "the Expedition-Scholar",        archetype: "Scholarly" },
  { id: "the_data_collector",            label: "the Data-Collector",            archetype: "Scholarly" },
  { id: "the_manuscript_finder",         label: "the Manuscript-Finder",         archetype: "Scholarly" },
  { id: "the_study_first",               label: "the Study-First",               archetype: "Scholarly" },
  { id: "the_always_learning",           label: "the Always-Learning",           archetype: "Scholarly" },
  { id: "the_theorist",                  label: "the Theorist",                  archetype: "Scholarly" },
  { id: "the_knowledge_seeker",          label: "the Knowledge-Seeker",          archetype: "Scholarly" },
  { id: "the_lore_transcriber",          label: "the Lore-Transcriber",          archetype: "Scholarly" },
  { id: "the_elder_text_reader",         label: "the Elder-Text Reader",         archetype: "Scholarly" },
  { id: "the_magic_analyst",             label: "the Magic-Analyst",             archetype: "Scholarly" },
  { id: "the_bookworm_warrior",          label: "the Bookworm-Warrior",          archetype: "Scholarly" },
  { id: "the_rune_keeper",               label: "the Rune-Keeper",               archetype: "Scholarly" },
  { id: "the_arcane_naturalist",         label: "the Arcane-Naturalist",         archetype: "Scholarly" },
];

// ─── Devout (50) — faction-aligned, prefers aligned zones, divine narrative ───
const DEVOUT: GhostPersonalityDef[] = [
  { id: "the_holy_crusader",            label: "the Holy Crusader",            archetype: "Devout" },
  { id: "the_faithful_servant",         label: "the Faithful Servant",         archetype: "Devout" },
  { id: "the_divine_champion",          label: "the Divine Champion",          archetype: "Devout" },
  { id: "the_pious",                    label: "the Pious",                    archetype: "Devout" },
  { id: "the_devoted",                  label: "the Devoted",                  archetype: "Devout" },
  { id: "the_believer",                 label: "the Believer",                 archetype: "Devout" },
  { id: "the_true_follower",            label: "the True Follower",            archetype: "Devout" },
  { id: "the_righteous",                label: "the Righteous",                archetype: "Devout" },
  { id: "the_holy_warrior",             label: "the Holy Warrior",             archetype: "Devout" },
  { id: "the_zealot",                   label: "the Zealot",                   archetype: "Devout" },
  { id: "the_missionary",               label: "the Missionary",               archetype: "Devout" },
  { id: "the_confessor",                label: "the Confessor",                archetype: "Devout" },
  { id: "the_penitent",                 label: "the Penitent",                 archetype: "Devout" },
  { id: "the_consecrated",              label: "the Consecrated",              archetype: "Devout" },
  { id: "the_blessed",                  label: "the Blessed",                  archetype: "Devout" },
  { id: "the_chosen",                   label: "the Chosen",                   archetype: "Devout" },
  { id: "the_faction_first",            label: "the Faction-First",            archetype: "Devout" },
  { id: "the_oath_keeper",              label: "the Oath-Keeper",              archetype: "Devout" },
  { id: "the_temple_guardian",          label: "the Temple Guardian",          archetype: "Devout" },
  { id: "the_divine_instrument",        label: "the Divine Instrument",        archetype: "Devout" },
  { id: "the_humble_servant",           label: "the Humble Servant",           archetype: "Devout" },
  { id: "the_flock_leader",             label: "the Flock-Leader",             archetype: "Devout" },
  { id: "the_proselytizer",             label: "the Proselytizer",             archetype: "Devout" },
  { id: "the_crusade_minded",           label: "the Crusade-Minded",           archetype: "Devout" },
  { id: "the_holy_purpose_driven",      label: "the Holy-Purpose Driven",      archetype: "Devout" },
  { id: "the_deity_guided",             label: "the Deity-Guided",             archetype: "Devout" },
  { id: "the_faith_rewarded",           label: "the Faith-Rewarded",           archetype: "Devout" },
  { id: "the_never_doubts",             label: "the Never-Doubts",             archetype: "Devout" },
  { id: "the_true_believer",            label: "the True Believer",            archetype: "Devout" },
  { id: "the_sacred_bound",             label: "the Sacred-Bound",             archetype: "Devout" },
  { id: "the_covenant_keeper",          label: "the Covenant-Keeper",          archetype: "Devout" },
  { id: "the_rite_observer",            label: "the Rite-Observer",            archetype: "Devout" },
  { id: "the_ritual_follower",          label: "the Ritual-Follower",          archetype: "Devout" },
  { id: "the_prayer_guided",            label: "the Prayer-Guided",            archetype: "Devout" },
  { id: "the_benediction_seeker",       label: "the Benediction-Seeker",       archetype: "Devout" },
  { id: "the_absolution_hunter",        label: "the Absolution-Hunter",        archetype: "Devout" },
  { id: "the_martyr_aspiring",          label: "the Martyr-Aspiring",          archetype: "Devout" },
  { id: "the_congregation_protector",   label: "the Congregation-Protector",   archetype: "Devout" },
  { id: "the_sanctuary_builder",        label: "the Sanctuary-Builder",        archetype: "Devout" },
  { id: "the_holy_light_follower",      label: "the Holy-Light Follower",      archetype: "Devout" },
  { id: "the_divine_will_executor",     label: "the Divine-Will Executor",     archetype: "Devout" },
  { id: "the_blessing_seeker",          label: "the Blessing-Seeker",          archetype: "Devout" },
  { id: "the_sanctified_warrior",       label: "the Sanctified Warrior",       archetype: "Devout" },
  { id: "the_ordained",                 label: "the Ordained",                 archetype: "Devout" },
  { id: "the_grace_embodied",           label: "the Grace-Embodied",           archetype: "Devout" },
  { id: "the_sermon_giver",             label: "the Sermon-Giver",             archetype: "Devout" },
  { id: "the_devout_at_heart",          label: "the Devout at Heart",          archetype: "Devout" },
  { id: "the_altar_keeper",             label: "the Altar-Keeper",             archetype: "Devout" },
  { id: "the_faith_bound",              label: "the Faith-Bound",              archetype: "Devout" },
  { id: "the_inquisitor_at_heart",      label: "the Inquisitor-at-Heart",      archetype: "Devout" },
];

// ─── Full catalog ─────────────────────────────────────────────────────────────

export const PERSONALITY_CATALOG: GhostPersonalityDef[] = [
  ...AGGRESSIVE,
  ...CAUTIOUS,
  ...EXPLORER,
  ...GREEDY,
  ...SCHOLARLY,
  ...DEVOUT,
];

// Build fast-lookup maps
const CATALOG_BY_LABEL = new Map<string, GhostPersonalityDef>(
  PERSONALITY_CATALOG.map(p => [p.label, p]),
);
const CATALOG_BY_ID = new Map<string, GhostPersonalityDef>(
  PERSONALITY_CATALOG.map(p => [p.id, p]),
);

// The 6 archetype names for backward-compat lookup
const ARCHETYPE_SET = new Set<string>(["Aggressive", "Cautious", "Explorer", "Greedy", "Scholarly", "Devout"]);

/**
 * Given a personality label (e.g. "the Berserker") or archetype name (e.g. "Aggressive"),
 * returns the corresponding GhostPersonality archetype.
 * Falls back to "Aggressive" if unknown.
 */
export function getArchetype(personality: string): GhostPersonality {
  // Direct archetype name — backward compat with old ghost data
  if (ARCHETYPE_SET.has(personality)) return personality as GhostPersonality;
  // Label lookup (e.g. "the Berserker")
  const byLabel = CATALOG_BY_LABEL.get(personality);
  if (byLabel) return byLabel.archetype;
  // ID lookup (e.g. "the_berserker")
  const byId = CATALOG_BY_ID.get(personality);
  if (byId) return byId.archetype;
  return "Aggressive";
}
